# -- Main Menu --

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

# [[main]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

[[main]]
  name = "Projects"
  pageRef = "Projects"
  weight = 30

# [[main]]
#   identifier = "web"
#   pre = "link"
#   url = "https://nunocoracao.github.io/blowfish/"
#   weight = 35

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/GoldenStone02"
  weight = 40

# -- Footer Menu --

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
